INSERT INTO `part_types` (`id_part_type`, `collation`, `name`, `description`, `family`, `id_part_collection`, `enabled`) VALUES
    (3, 30, 'Alto Flute', 'The alto flute has a deeper range and more powerful tone.', 'Woodwind', 1, 1),
    (4, 40, 'Oboe', 'The oboe is a type of double reed woodwind instrument.', 'Woodwind', 1, 1),
    (5, 50, 'English Horn', 'The English horn', 'Woodwind', 1, 1),
    (6, 60, 'Bassoon', 'The bassoon is a woodwind instrument in the double reed family, which has a tenor and bass sound.', 'Woodwind', 1, 1),
    (7, 70, 'Contrabassoon', 'The contrabassoon, also known as the double bassoon, is a larger version of the bassoon, sounding an octave lower.', 'Woodwind', 1, 0),
    (8, 80, 'Clarinet in Eb', 'The E-flat (E♭) clarinet is a member of the clarinet family, smaller than the more common B♭ clarinet and pitched a perfect fourth higher.', 'Woodwind', 1, 1),
    (9, 90, 'Clarinet in Bb', 'The clarinet has a single-reed mouthpiece, a straight, cylindrical tube with an almost cylindrical bore, and a flared bell.', 'Woodwind', 1, 1),
    (10, 100, 'Bass Clarinet', 'Bass clarinet is usually pitched in B♭ (meaning it is a transposing instrument on which a written C sounds as B♭), but it plays notes an octave below the soprano B♭ clarinet.', 'Woodwind', 1, 1),
    (11, 110, 'Soprano Saxophone', 'The soprano saxophone is a higher-register variety of the saxophone.', 'Woodwind', 1, 1),
    (12, 120, 'Alto Saxophone', 'The saxophone is a type of single-reed woodwind instrument with a conical body, usually made of brass.', 'Woodwind', 1, 1),
    (13, 130, 'Tenor Saxophone', 'The tenor saxophone is a medium-sized type of single-reed woodwind instrument with a conical body, usually made of brass.', 'Woodwind', 1, 1),
    (14, 140, 'Baritone Saxophone', 'The baritone saxophone is a type of single-reed woodwind instrument with a conical body, usually made of brass.', 'Woodwind', 1, 1),
    (15, 150, 'Bass Saxophone', 'The bass saxophone is a type of single-reed woodwind instrument with a conical body, usually made of brass.', 'Woodwind', 1, 1),
    (16, 160, 'Horn in F', 'The French horn (since the 1930s known simply as the "horn" in professional music circles) is a brass instrument made of tubing wrapped into a coil with a flared bell.', 'Brass', 1, 0),
    (17, 170, 'Trumpet in Bb', 'The trumpet is a brass instrument commonly used in classical and jazz ensembles.', 'Brass', 1, 1),
    (18, 180, 'Trombone', 'Trombone is a brass instrument an extendable slide that can increase the length of the instruments tubing.', 'Brass', 1, 1),
    (19, 190, 'Bass Trombone', 'A variation of the trombone family, considered the lower member of the trombone family.', 'Brass', 1, 1),
    (20, 200, 'Baritone', 'The baritone horn, or sometimes just called baritone, is a valved, low-pitched brass instrument.', 'Brass', 1, 1),
    (21, 210, 'Euphonium', 'Euphonium, a brass wind instrument with valves, is the leading instrument in the tenor-bass range in military bands.', 'Brass', 1, 1),
    (22, 220, 'Tuba', 'The tuba is the lowest-pitched musical instrument in the brass family.', 'Brass', 1, 1),
    (23, 230, 'Timpani', 'Timpani or kettledrums are musical instruments in the percussion family.', 'Percussion', 1, 1),
    (24, 240, 'Cymbals', 'A cymbal is a common percussion instrument. Often used in pairs, cymbals consist of thin, normally round plates of various alloys.', 'Percussion', 1, 1),
    (25, 250, 'Agogo bells', 'An agogô (Yoruba: agogo, meaning bell) is a single or a multiple bell', 'Percussion', 1, 1),
    (26, 260, 'Triangle','The triangle is an idiophone type of musical instrument in the percussion family.', 'Percussion', 1, 1),
    (27, 270, 'Tam-Tam','A gong of indefinite pitch.', 'Percussion', 1, 1),
    (28, 280, 'Tambourine','The tambourine is a musical instrument in the percussion family consisting of a frame, often of wood or plastic, with pairs of small metal jingles, called "zills".', 'Percussion', 1, 1),
    (29, 290, 'Snare drum','The snare drum or side drum is a percussion instrument that produces a sharp staccato sound when the head is struck with a drum stick.', 'Percussion', 1, 1),
    (30, 300, 'Bass drum','The bass drum, or kick drum, is a large drum that produces a note of low definite or indefinite pitch.', 'Percussion', 1, 1),
    (31, 310, 'Marimba','A percussion instrument consisting of a set of wooden bars struck with yarn or rubber mallets to produce musical tones.', 'Percussion', 1, 1),
    (32, 320, 'Vibraphone','A percussion instrument that has tuned metal bars.', 'Percussion', 1, 1),
    (33, 330, 'Xylophone','A percussion instrument consisting of a set of graduated, tuned wooden bars supported at nodal (nonvibrating) points and struck with sticks or padded mallets.', 'Percussion', 1, 1),
    (34, 340, 'Chimes','Also called tubular bells, chimes produce a sound that resembles church bells, or a carillon.', 'Percussion', 1, 1),
    (35, 350, 'Harp','The harp is a stringed musical instrument that has a number of individual strings running at an angle to its soundboard; the strings are plucked with the fingers.', 'Percussion', 1, 1),
    (36, 360, 'Piano','The piano is an acoustic, stringed musical instrument in which the strings are struck by wooden hammers and is played using a keyboard.', 'Percussion', 1, 1),
    (37, 370, 'String Bass',' The double bass, also known simply as the bass, is the largest and lowest-pitched bowed (or plucked) string instrument.', 'Strings', 1, 1);